[package]
name = "z-claw-cli"
license.workspace = true
homepage.workspace = true
repository.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
z-claw-core.workspace = true
z-claw-config.workspace = true
z-claw-agent.workspace = true
z-claw-providers.workspace = true
z-claw-tools.workspace = true
z-claw-memory.workspace = true
z-claw-security.workspace = true
z-claw-skills.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
